const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');
let p=path.join(root,'screens/ProfileScreen.js'),s=fs.readFileSync(p,'utf8');fs.copyFileSync(p,path.join(__dirname,'implementation-baseline/ProfileScreen.js'));
s="import ProfileExtras from '../components/ProfileExtras';\nimport { getProfileCoverage, isValidState } from '../utils/matching';\n"+s;
s=s.replace(/function computeProfileStrength\(user\) \{[\s\S]*?\n}/,'function computeProfileStrength(user) { return getProfileCoverage(user).percent; }');
s=s.replace('export default function ProfileScreen({ navigation }) {','export default function ProfileScreen({ navigation }) {\n const [extrasVisible,setExtrasVisible] = useState(false);');
if(!s.includes('[extrasVisible')){const i=s.indexOf('export default function ProfileScreen(');const b=s.indexOf('{',s.indexOf(')',i));s=s.slice(0,b+1)+'\n const [extrasVisible,setExtrasVisible] = useState(false);'+s.slice(b+1);}
s=s.replace('>Profile Strength<','>Profile completeness<').replace('Add your GPA range and application materials to surface more fitting programs.','Confirm your home location and practical limits to complete your profile.').replace('Great profile! Your feed is highly personalized.','Your basic preferences are complete. Check each program’s requirements before applying.').replace('>Improve profile<','>Complete preferences<');
s=s.replace(" <SettingsSection title=\"Account\">", " <ProfileExtras visible={extrasVisible} onClose={() => setExtrasVisible(false)} />\n <SettingsSection title=\"Your matches\">\n <SettingsRow label=\"Adjust matching preferences\" sublabel=\"Interests, home location, commute and compensation\" onPress={() => navigation.navigate('Onboarding',{edit:true})} />\n <SettingsRow label=\"School, dates & selectivity\" sublabel=\"Optional details, separate from your home location\" onPress={() => setExtrasVisible(true)} />\n </SettingsSection>\n <SettingsSection title=\"Account\">");
s=s.replace(" const autoState = extractStateAbbrev(location);"," const autoState = extractStateAbbrev(location);\n if (location.trim() && (!autoState || !isValidState(autoState))) { Alert.alert('Check your location','Use City, ST with a valid US state abbreviation.'); return; }");
s=s.replace(' name,\n location,\n grade,',' name,\n location,\n city: location.split(\',\')[0].trim(),\n locationConfirmed: !!autoState,\n locationSource: \'home\',\n grade,');
s=s.replace("label: 'Prestige & selectivity'", "label: 'Program selectivity'");
// The old competitiveness weight no longer affects fit; remove its control.
s=s.replace(/ \{ key: 'competitiveness',[\s\S]*?\},\r?\n/,'');
fs.writeFileSync(p,s);
p=path.join(root,'utils/schools.js');s=fs.readFileSync(p,'utf8').replace('query, state, limit = 8)','query, state, limit = 8, options = {})').replace("      console.warn('[schools] search failed:', err2.message);","      if (options.throwOnError) throw err2;\n      console.warn('[schools] search failed:', err2.message);");fs.writeFileSync(p,s);
p=path.join(root,'screens/HomeScreen.js');s=fs.readFileSync(p,'utf8').replaceAll('const safeUser = user || {};','const safeUser = user;');fs.writeFileSync(p,s);
p=path.join(root,'utils/matching.js');s=fs.readFileSync(p,'utf8').replace(/function gradeNumFitLevel\([\s\S]*?\n}\n/,'').replace("if(b.eligibility.unknown || b.practical.status==='unknown')return 'Needs confirmation';","if(b.checksNeeded.length)return 'Needs confirmation';").replace("if(b.eligibility.unknown || b.practical.status==='unknown' || b.total===null)return 1;","if(b.checksNeeded.length || b.total===null)return 1;");fs.writeFileSync(p,s);
